- CHANGELOG.md
- app.py
New metrics `_METRIC_PACKAGES_NEW_AND_NOTIFIED` and `_METRIC_PACKAGES_RELEASES_TIME`, to track 'Packages newly added and notification send' and 'Runtime of package releases job'.
> added a few more metrics

- Pipfile
> Pin down PyYaml due to aiogremlin version pinning

- .zuul.yaml
- openshift/cronJob-template.yaml
Signed-off-by: Christoph Görn <goern@redhat.com>
> added image stream tag and namespace parameter

- openshift/buildConfig-template.yaml
- openshift/cronJob-template.yaml
- openshift/imageStream-template.yaml
Required the fix for deployment in the new cluster.
> fix template for openshift >=3.11

- app.py
- openshift/cronJob-template.yaml
> Standardize environment variables and metrics

- app.py
Fixes: #187
Depends-On: https://github.com/thoth-station/storages/pull/790
> Fix issues with old method

- README.rst
> State how to run against local deployment

- config/thoth.yaml
> Add untrahook to send package release notifications to

- Pipfile
- Pipfile.lock
- app.py
Signed-off-by: Christoph Görn <goern@redhat.com>
> relocked dependencies to fix CVE-2017-18342

- app.py
> Update query functions according to new naming convention

- app.py
> Fix reversed return value in checks in release monitoring

- app.py
Fixes: https://github.com/thoth-station/package-releases-job/issues/275
> Fix API Call Error

- app.py
use Prometheus collector Registry
Fixes: #283 
> use Prometheus collector Registry

- app.py
> Use correct query to obtain Python package index configuration

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/major-release.md
- .github/ISSUE_TEMPLATE/minor-release.md
- .github/ISSUE_TEMPLATE/patch-release.md
include github issue templates
Fixes: #419 
> include github issue templates

- .env.template
- Pipfile
- Pipfile.lock
- app.sh
- producer.py
- version.py
Fixes: https://github.com/thoth-station/package-releases-job/issues/446
> make package-release-job a producer

- app.sh
To run `package-release-job` as a producer.
Related-To: https://github.com/thoth-station/thoth-application/pull/425
> run safely

- .aicoe-ci.yaml
enable aicoe-ci to build and deploy
> enable aicoe-ci to build and deploy

- producer.py
Related-To: https://github.com/thoth-station/messaging/pull/248
> fix import PackageReleasedMessage

- producer.py
To test `package-releases-job` in debug mode.
> Be verbose

- producer.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/529
reopened to solve issues with commits: https://github.com/thoth-station/package-releases-job/pull/532 @fridex
> Add database metric

- .pre-commit-config.yaml
- Pipfile
- Pipfile.lock
- app.sh
- producer.py
Use confluent kafka producer for messages. No longer require async tasks.
This should not affect performance because `confluent-kafka` wraps `librdkafka` which batches messages and sends them asynchronously.
> update to latest messaging

- producer.py
Related-To: https://github.com/thoth-station/messaging/issues/355
> Adjust label metrics

- .pre-commit-config.yaml
- .prow.yaml
- Pipfile
- Pipfile.lock
- mypy.ini
- producer.py
> use thoth-messaging >=0.14

- Pipfile.lock
- producer.py
if program terminates before messages are sent by librdkafka they will be lost. `flush` will send all pending messages.
> flush all pending messages

- mypy.ini
mypy error fix for package-releases-job
> mypy error fix for package-releases-job

- .prow.yaml
- mypy.ini
updated the mypy config to better handle issues
> updated the mypy config to better handle issues

- README.rst
- mypy.ini
set badges for easy access to content
> set badges for easy access to content

- Pipfile.lock
- producer.py
> Update thoth-python library

- Pipfile.lock
Merging manually as this is already tested and works.
> Dependency update to have new thoth-python

- producer.py
> Expose thoth-python version

- .thoth.yaml
- .thothTemplate.yaml
> Enable TLS verification

- .pre-commit-config.yaml
- .prow.yaml
Git protocol is disabled on github
> Use https for pre-commits

- .pre-commit-config.yaml
- .prow.yaml
- .thoth.yaml
- OWNERS
- Pipfile.lock
Updated the dependencies and prow config
Fixes: #650
> :hatched_chick: Updated the dependencies and prow config

- .pre-commit-config.yaml
- OWNERS
- producer.py
HouseKeeping: Updated pre-commit and fix mypy issue
> :recycle: HouseKeeping: Updated pre-commit and fix mypy issue
